empty_props = {
    'path_list': None,
    'was_routed': None,
    'topology': None,
    'net_spec_dict': None,
    'req_id': None,
    'source': None,
    'destination': None,
    'bandwidth': None,
    'bandwidth_list': list(),
    'modulation_list': list(),
    'core_list': list(),
    'xt_list': list(),
    'stat_key_list': ['modulation_list', 'xt_list', 'core_list'],
    'num_trans': None,
    'slots_needed': None,
    'single_core': False,
    'block_reason': None,
}
