name: Slack Notifications

on:
  pull_request:
    branches:
      - main
  issues:
    branches:
      - main
  create:
    branches:
      - main
    types: [ tag ]

jobs:

  slack-notifications:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    name: Sends a message to Slack when a pull request, issue, or new tag is made

    steps:
      - name: Send Slack Message for Pull Request
        if: github.event_name == 'pull_request'
        uses: archive/github-actions-slack@v2.0.0
        id: send-pr-message
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C05LW0SGL6N
          slack-text: |
            *New Event In* `${{ github.repository }}`
            - *Type:* ${{ github.event_name }}
            - *Title:* ${{ github.event.pull_request.title }}
            - *Workflow creator:* ${{ github.actor }}
            - *Workflow actor:* ${{ github.triggering_actor }}
            - *Branch:* `${{ github.head_ref }}`

      - name: Send Slack Reaction To Message
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-function: send-reaction
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.channel }}
          slack-emoji-name: zombie
          slack-message-timestamp: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.message.ts }}

      - name: Send Slack Reaction To Message
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-function: send-reaction
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.channel }}
          slack-emoji-name: omnetpp_logo
          slack-message-timestamp: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.message.ts }}

      - name: Send Slack Reaction To Message
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-function: send-reaction
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.channel }}
          slack-emoji-name: mage
          slack-message-timestamp: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.message.ts }}

      - name: Send Slack Reaction To Message
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-function: send-reaction
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.channel }}
          slack-emoji-name: mailbox_with_mail
          slack-message-timestamp: ${{ fromJson(steps.send-pr-message.outputs.slack-result).response.message.ts }}

      - name: Send Slack Message for Issues
        if: github.event_name == 'issues'
        uses: archive/github-actions-slack@v2.0.0
        id: send-issue-message
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C05LW0SGL6N
          slack-text: |
            *New Event In* `${{ github.repository }}`
            - *Type:* ${{ github.event_name }}
            - *Title:* ${{ github.event.issue.title }}
            - *Workflow creator:* ${{ github.actor }}
            - *Workflow actor:* ${{ github.triggering_actor }}
            - *Branch:* `${{ github.head_ref }}`


      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"